<?php $session = $this->session->userdata('username'); // check for session data
   // Team of the month >> s2s and realtors
   $s2s_team_tm = array('s2s_team' => $s2s_teams[0]->team_name, 's2s_revenue' => $s2s_teams[0]->received_amount);
   $realtors_team_tm = array('realtors_team' => $realtors[0]->team_name, 'realtors_revenue' => $realtors[0]->amount_received);
   // Runner-up of the month >> s2s and realtors
   $s2s_team_rm = array('s2s_team' => $s2s_teams[1]->team_name, 's2s_revenue' => $s2s_teams[1]->received_amount);
   $realtors_team_rm = array('realtors_team' => $realtors[1]->team_name, 'realtors_revenue' => $realtors[1]->amount_received);
   // Team of the month to be printed on the board >> s2s and realtors
   $team_of_the_month = $s2s_team_tm['s2s_revenue'] > $realtors_team_tm['realtors_revenue'] ? $s2s_team_tm['s2s_team'] : $realtors_team_tm['realtors_team'];
   $tm_revenue = $s2s_team_tm['s2s_revenue'] > $realtors_team_tm['realtors_revenue'] ? $s2s_team_tm['s2s_revenue'] : $realtors_team_tm['realtors_revenue'];
   // Runener-up of the month to be printed on the board >> s2s and realtors
   $rm_of_the_month = $s2s_team_rm['s2s_revenue'] > $realtors_team_rm['realtors_revenue'] ? $s2s_team_rm['s2s_team'] : $realtors_team_rm['realtors_team'];
   $rm_revenue = $s2s_team_rm['s2s_revenue'] > $realtors_team_rm['realtors_revenue'] ? $s2s_team_rm['s2s_revenue'] : $realtors_team_rm['realtors_revenue'];
   // Agent of the month >> s2s and realtors
   $s2s_agent = array('s2s_agent_m' => $daily_sales[0]->emp_name, 's2s_agent_revenue' => $daily_sales[0]->received_amount);
   $realtors_agent = array('realtors_agent_m' => $realtors_sales[0]->name, 'realtors_agent_revenue' => $realtors_sales[0]->amount_received);
   // Agent of the month to be printed on the board >> s2s and realtors
   $agent_of_the_month = $s2s_agent['s2s_agent_revenue'] > $realtors_agent['realtors_agent_revenue'] ? $s2s_agent['s2s_agent_m'] : $realtors_agent['realtors_agent_m'];
   $agent_of_the_month_revenue = $s2s_agent['s2s_agent_revenue'] > $realtors_agent['realtors_agent_revenue'] ? $s2s_agent['s2s_agent_revenue'] : $realtors_agent['realtors_agent_revenue'];
   // highest sales by office >> s2s and realtors
   $kohat_office = 0; $hangu_office = 0; $psh_office = 0; $realtors_office = 0; // declare variables and assign a value of 0.
   $highest_office_by_revenue = ''; // declare variable for highest office by revenue and concatenate the office name
   $highest_office_revenue = ''; // declare variable for highest office revenue and concatenate the office revenue
   foreach($daily_sales as $ds){ // loop through the values of s2s
      if($ds->emp_city == 'Kohat'){
         $kohat_office += $ds->received_amount;
      }elseif($ds->emp_city == 'Hangu'){
         $hangu_office += $ds->received_amount;
      }elseif($ds->emp_city == 'Peshawar'){
         $psh_office += $ds->received_amount;
      }
   }
   foreach($realtors_sales as $rs){ // loop through the value of realtors
      $realtors_office += $rs->amount_received;
   }
   if($kohat_office > $hangu_office && $kohat_office > $psh_office){ // check for highest office by revenue
      $highest_office_by_revenue .= 'Kohat';  // highest office by revenue >> name will be displayed
      $highest_office_revenue .= $kohat_office; // print the revenue generated by that specific office.
   }elseif($psh_office > $hangu_office && $psh_office > $kohat_office){ // check for highest office by revenue
      $highest_office_by_revenue .= 'Peshawar';
      $highest_office_revenue .= $psh_office;
   }elseif($hangu_office > $psh_office && $hangu_office > $kohat_office){ // check for highest office by revenue
      $highest_office_by_revenue .= 'Hangu';
      $highest_office_revenue .= $hangu_office;
   }elseif($realtors_office > $psh_office && $realtors_office > $hangu_office && $realtors_office > $kohat_office){
      $highest_office_by_revenue .= 'Realtors';
      $highest_office_revenue .= $realtors_office;
   }
?>
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta http-equiv="refresh" content="300">
      <link rel="stylesheet" href="<?php echo base_url('assets/css/bootstrap.min.css'); ?>">
      <link rel="stylesheet" href="<?php echo base_url('assets/css/fontawesome-all.min.css'); ?>">
      <script src="<?php echo base_url('assets/js/jquery.min.js'); ?>"></script>
      <script src="<?php echo base_url('assets/js/bootstrap.min.js'); ?>"></script>
      <title>
         <?php if($session ){ echo 'Sales Competition &raquo; S2S Marketing & Realtors | Daily Sales'; } ?>
      </title>
   </head>
   <style>
      .s2s{ color:#23bca1; }
      .realtors{ color:#732dd9; }
   </style>
   <body>
      <?php if($this->session->userdata('username')): ?>
         <div class="container-fluid">
            <div class="row pt-3 pb-3">
               <div class="col-md-3 col-sm-12">
                  <h4 class="mt-1 mb-0">Sales Competition</h4>
               </div>
               <div class="col-md-6 col-sm-8 text-center">
                  <h3 class="mb-0"><span class="font-weight-bold s2s">S2S Marketing</span> <small class="text-muted">vs</small> <span class="font-weight-bold realtors">Realtors PK</span></h3>
               </div>
               <div class="col-md-3 col-sm-4 text-right">
                  <a href="javascript: history.go(-1)" class="btn btn-outline-secondary mt-0">Back Home</a>
               </div>
            </div>
            <div class="row">
               <div class="col-md-12">
                  <div class="card-deck">
                     <div class="card">
                        <div class="card-header">
                           <h4 class="card-title font-weight-light">S2S Marketing - This Month</h4>
                        </div>
                        <div class="card-body table-responsive">
                           <table class="table table-condensed table-sm">
                              <thead>
                                 <tr>
                                    <th>Team</th>
                                    <th>Target</th>
                                    <th>Revenue</th>
                                    <th>%age to Target</th>
                                 </tr>
                              </thead>
                              <tbody>
                                 <?php if(!empty($s2s_teams)):
                                 $class = 0;
                                 $bcm1_target = 0; $bcm1_revenue = 0; // BCM-I in Psh
                                 $bcm2_target = 0; $bcm2_revenue = 0; // BCM-II in Psh
                                 $bcm3_target = 0; $bcm3_revenue = 0; // BCM-III in Psh 
                                 $bcmh_target = 0; $bcmh_revenue = 0; // BCM in Hangu
                                 $bcmk_target = 0; $bcmk_revenue = 0; // BCM in Hangu
                                 $mgt_target = 0; $mgt_revenue = 0; // BCM in Management
                                 foreach($s2s_teams as $team_rep): $class++; ?>
                                 <tr>
                                    <td><?= $team_rep->team_name; ?></td>
                                    <td><?php $team_target =  $this->home_model->sum_targets($team_rep->team_id); 
                                    if($team_target->team_lead == 'BCM-I'){ 
                                       $bcm1_target += $team_target->total_targets; 
                                       $bcm1_revenue += $team_rep->received_amount;  
                                    }elseif($team_target->team_lead == 'BCM-II'){ 
                                       $bcm2_target += $team_target->total_targets; 
                                       $bcm2_revenue += $team_rep->received_amount;
                                    }elseif($team_target->team_lead == 'BCM-III'){
                                       $bcm3_target += $team_target->total_targets; 
                                       $bcm3_revenue += $team_rep->received_amount;
                                    }elseif($team_target->team_lead == 'BCMH-I'){ 
                                       $bcmh_target += $team_target->total_targets; 
                                       $bcmh_revenue += $team_rep->received_amount;
                                    }elseif($team_target->team_lead == 'BCMK-I'){ 
                                       $bcmk_target += $team_target->total_targets; 
                                       $bcmk_revenue += $team_rep->received_amount;
                                    }elseif($team_target->team_lead == 'Management'){ 
                                       $mgt_target += $team_target->total_targets; 
                                       $mgt_revenue += $team_rep->received_amount;
                                    }
                                    echo number_format($team_target->total_targets/1000000, 2); ?></td>
                                    <td><?= number_format($team_rep->received_amount/1000000, 2); ?></td>
                                    <td>
                                       <?= $team_target->total_targets > 0 ? number_format($team_rep->received_amount/$team_target->total_targets*100, 1).' %' : '0.0 %'; ?>
                                    </td>
                                 </tr>
                                 <?php endforeach; endif; ?>
                              </tbody>
                           </table>
                        </div>
                     </div>
                     <div class="card">
                        <div class="card-header">
                           <h4 class="card-title font-weight-light">Sales Competition</h4>
                        </div>
                        <div class="card-body table-responsive">
                           <table class="table table-condensed table-bordered table-sm">
                              <tbody>
                                 <tr align="center">
                                    <th colspan="2">Sales Champ</th>
                                 </tr>
                                 <tr align="center">
                                    <td class="w-50">BCM-I</td>
                                    <td class="w-50">20M</td>
                                 </tr>
                                 <tr align="center">
                                    <th colspan="2">Highest Revenue - Office</th>
                                 </tr>
                                 <tr align="center">
                                    <td class="w-50"><?= $highest_office_by_revenue; ?></td>
                                    <td class="w-50"><?= !empty($highest_office_revenue) ? number_format($highest_office_revenue/1000000, 2).' M' : '0'; ?></td>
                                 </tr>
                                 <tr align="center">
                                    <th colspan="2">Highest Revenue - Agent</th>
                                 </tr>
                                 <tr align="center">
                                    <td class="w-50"><?= $agent_of_the_month; ?></td>
                                    <td class="w-50"><?= number_format($agent_of_the_month_revenue/1000000, 2).' M'; ?></td>
                                 </tr>
                                 <tr align="center">
                                    <th colspan="2">Team of the Month</th>
                                 </tr>
                                 <tr align="center">
                                    <td class="w-50"><?= $team_of_the_month; ?></td>
                                    <td class="w-50"><?= number_format($tm_revenue/1000000, 2).' M'; ?></td>
                                 </tr>
                                 <tr align="center">
                                    <th colspan="2">Runner-up of the Month</th>
                                 </tr>
                                 <tr align="center">
                                    <td class="w-50"><?= $rm_of_the_month; ?></td>
                                    <td class="w-50"><?= number_format($rm_revenue/1000000, 2).' M'; ?></td>
                                 </tr>
                              </tbody>
                           </table>
                        </div>
                     </div>
                     <div class="card">
                        <div class="card-header">
                           <h4 class="card-title font-weight-light">RealtorsPK</h4>
                        </div>
                        <div class="card-body table-responsive">
                           <table class="table table-condensed table-sm">
                              <thead>
                                 <tr>
                                    <th>Team</th>
                                    <th>Target</th>
                                    <th>Revenue</th>
                                    <th>%age to Target</th>
                                 </tr>
                              </thead>
                              <tbody>
                                 <?php if(!empty($realtors)): foreach($realtors as $realtor): ?>
                                 <?php $targets = $this->home_model->sum_targets_realtors($realtor->team_id); ?>
                                    <tr>
                                       <td><?= $realtor->team_name ? $realtor->team_name : '--'; ?></td>
                                       <td><?= !empty($targets->total_targets) ? number_format($targets->total_targets/1000000, 2) : '0.00'; ?></td>
                                       <td><?= number_format($realtor->amount_received/1000000, 2); ?></td>
                                       <td><?= !empty($targets->total_targets) ? number_format($realtor->amount_received/$targets->total_targets*100, 2).'%' : '0.00%'; ?></td>
                                    </tr>
                                 <?php endforeach; endif; ?>
                              </tbody>
                           </table>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
            <div class="row">
               <div class="col-md-12 text-right">
                  <small>&copy; <?= date('Y'); ?>, AH Group of Companies Pvt. Ltd.</small>
               </div>
            </div>
         </div>
      <?php else: ?>
         <div class="container-fluid mt-4 mb-4">
            <div class="row">
               <div class="col-md-12">
                  <div class="alert alert-danger">
                     <h2 class="font-weight-light">
                        Whoops! Looks like you're not logged in.
                     </h2>
                  </div>
               </div>
            </div>
         </div>
      <?php endif; ?>
   </body>
</html>